# Generated by Django 4.0.3 on 2022-04-01 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new', '0004_alter_comment_name_alter_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
